# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-22 03:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobTracker', '0002_jobsharetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reltype', models.CharField(choices=[(0, 'friend'), (1, 'pending1'), (2, 'pending2')], max_length=1)),
                ('user_first_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtracker_friendstable_related', to=settings.AUTH_USER_MODEL)),
                ('user_second_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
