# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobTracker', '0004_auto_20161021_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsharetable',
            name='fromUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtracker_jobsharetable_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobsharetable',
            name='jobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobTracker.TJob'),
        ),
        migrations.AlterField(
            model_name='jobsharetable',
            name='toUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
